specVersion: 0.2.1
description: Blocks
repository: https://github.com/zenlinkpro/moonriver-blocks-subquery
schema:
  file: ./schema.graphql
network:
  chainId: '0x91bc6e169807aaa54802737e1c504b2577d4fafedd5a02c10293b1cd60e39527'
  endpoint: 'wss://moonbeam-alpha.api.onfinality.io/public-ws'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 790834
    processor:
      file: './node_modules/@subql/contract-processors/dist/moonbeam.js'
      options:
        abi: Factory
        address: '0xf36AE63d89983E3aeA8AaaD1086C3280eb01438D'
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
